#!/bin/sh

if [ ! -e /conf/elasticsearch.* ]; then
  cp $ES_HOME/config/elasticsearch.yml /conf
fi

if [ ! -e /conf/logging.* ]; then
  cp $ES_HOME/config/logging.yml /conf
fi

OPTS="-Des.path.conf=/conf \
  -Des.path.data=/data \
  -Des.path.logs=/data" 

OPTS="$OPTS -Des.insecure.allow.root=true"
if [ -n "$NODE_PORT" ]; then
  OPTS="$OPTS -Des.transport.tcp.port=$NODE_PORT"
fi

if [ -n "$HTTP_PORT" ]; then
  OPTS="$OPTS -Des.http.port=$HTTP_PORT"
fi	

if [ -n "$CLUSTER" ]; then
  OPTS="$OPTS -Des.cluster.name=$CLUSTER"
fi

if [ -n "$NODE_NAME" ]; then
  OPTS="$OPTS -Des.node.name=$NODE_NAME"
fi

if [ -n "$UNICAST_HOSTS" ]; then
  OPTS="$OPTS -Des.discovery.zen.ping.unicast.hosts=$UNICAST_HOSTS"
fi

if [ -n "$PUBLISH_AS" ]; then
  OPTS="$OPTS --network.host $PUBLISH_AS "
  #OPTS="$OPTS -Des.transport.publish_port=$(echo $PUBLISH_AS | awk -F: '{if ($2) print $2; else print 9300}')"
fi

echo "Starting Elasticsearch with the options $OPTS"
$ES_HOME/bin/elasticsearch $OPTS
